### ISSUE TITLE
Meta-AutoSKLearn ran out of memory on large dataset

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/d3m-dynamic-neural-architecture#114]
```
meta_autosklearn regression ec93efaa-21cf-47c4-9fb3-ea5e90ea372f
[ERROR] [2019-07-19 17:36:18,126:AutoML(1):73a6cd0eae08d3bd91d6e2b5a647ff99] Error creating dummy predictions: {'error': 'Memout (used more than 3072 MB).', 'configuration_origin': 'DUMMY'} 
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".../d3m-dynamic-neural-architecture/dna/__main__.py", line 471, in <module>
    main(sys.argv)
  File ".../d3m-dynamic-neural-architecture/dna/__main__.py", line 467, in main
    handler(arguments, parser)
  File ".../d3m-dynamic-neural-architecture/dna/__main__.py", line 434, in handler
    evaluate_handler(arguments, subparser)
  File ".../d3m-dynamic-neural-architecture/dna/__main__.py", line 261, in evaluate_handler
    model_output_dir=model_output_dir, plot_dir=plot_dir
  File ".../d3m-dynamic-neural-architecture/dna/__main__.py", line 179, in evaluate
    train_data, model, model_config, verbose=verbose, model_output_dir=model_output_dir
  File ".../d3m-dynamic-neural-architecture/dna/problems.py", line 63, in fit_predict
    train_data, model, model_config, refit_model=refit_model, verbose=verbose, model_output_dir=model_output_dir
  File ".../d3m-dynamic-neural-architecture/dna/problems.py", line 41, in fit
    train_data, verbose=verbose, output_dir=model_output_dir, **model_fit_config
  File ".../d3m-dynamic-neural-architecture/dna/models/models.py", line 369, in fit
    self.regressor.fit(X_data, y)
  File ".../d3m-dynamic-neural-architecture/env/lib/python3.6/site-packages/autosklearn/estimators.py", line 802, in fit
    dataset_name=dataset_name,
  File ".../d3m-dynamic-neural-architecture/env/lib/python3.6/site-packages/autosklearn/estimators.py", line 337, in fit
    self._automl[0].fit(**kwargs)
  File ".../d3m-dynamic-neural-architecture/env/lib/python3.6/site-packages/autosklearn/automl.py", line 1091, in fit
    load_models=load_models,
  File ".../d3m-dynamic-neural-architecture/env/lib/python3.6/site-packages/autosklearn/automl.py", line 208, in fit
    only_return_configuration_space=only_return_configuration_space,
  File ".../d3m-dynamic-neural-architecture/env/lib/python3.6/site-packages/autosklearn/automl.py", line 384, in _fit
    num_run = self._do_dummy_prediction(datamanager, num_run)
  File ".../d3m-dynamic-neural-architecture/env/lib/python3.6/site-packages/autosklearn/automl.py", line 313, in _do_dummy_prediction
    raise ValueError("Dummy prediction failed: %s " % str(additional_info))
ValueError: Dummy prediction failed: {'error': 'Memout (used more than 3072 MB).', 'configuration_origin': 'DUMMY'} 
```

**Comment by bjschoenfeld** [comment]
fixed with 45c42b2803d73345bac12a56ccc8eb8f33a68094
